// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptytdkhelbrunangtazc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0eXRka2hlbGJydW5hbmd0YXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MjY0NDksImV4cCI6MjA1MzQwMjQ0OX0.G8pj6sSvogATbbgvay_8mOdG2csrk4LUWqunGlQGmYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);